// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jxcfjnnknwwnmmbhthup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4Y2Zqbm5rbnd3bm1tYmh0aHVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2MDEzMjUsImV4cCI6MjA1NzE3NzMyNX0.aSRhaKQr_QruJNXtSPsWc7ZavPi93A-Fdb7Ap7ypDe4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);